"""Add message field to GenerationTask

Revision ID: 0c0ee5e6745f
Revises: 
Create Date: 2025-09-10 02:18:52.412509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c0ee5e6745f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generation_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generation_task', schema=None) as batch_op:
        batch_op.drop_column('message')

    # ### end Alembic commands ###
