"""fix unique constraints for serial numbers

Revision ID: 9f32e4b97d76
Revises: 0c0ee5e6745f
Create Date: 2025-09-11 04:19:23.729109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f32e4b97d76'
down_revision = '0c0ee5e6745f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banknote', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_serial_side', ['serial_number', 'side'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banknote', schema=None) as batch_op:
        batch_op.drop_constraint('unique_serial_side', type_='unique')

    # ### end Alembic commands ###
